### ISSUE TITLE
Add HTTP2.

### ISSUE THREAD

**Issue by dragostis** [Anima-Engine/anima-engine.org#6]
This will make all these requests much faster.

**Comment by krodyrobi** [comment]
As far as I know  SPDY requires ssl connections, if this is so we should go for http2 from the start as SPDY is v1 of http2. The newer version has some major improvements in pipelining / header compression / no of handshakes etc.

**Comment by dragostis** [comment]
Sure, HTTP2 would be nice, but I don't really know if this is useful right now. Maybe if we upgrade the droplet to 1GB.

**Comment by krodyrobi** [comment]
https://www.nginx.com/blog/nginx-1-9-5/
https://letsencrypt.org/getting-started/

**Comment by dragostis** [comment]
@krodyrobi Sounds like a plan. Let's see how this works.

**Comment by krodyrobi** [comment]
Closed for now.
